---
- hosts: localhost
  connection: local
  vars:
    ssh_key_name: swarm
    ssh_key_path: ~/.ssh/id_rsa.pub
    aws_region: us-west-2
    swarm_num_head: 1
    swarm_num_node: 2
    swarm_security_group_name: swarm
    swarm_template: ami-efd0428f
    swarm_instance_type: t2.nano

  roles:
    - common
    - swarm
  
