# Create swarm security group and rules

  - name: Create Swarm Security Group
    ec2_group:
      name: "{{ swarm_security_group_name }}"
      description: Swarm Cluster
      region: "{{ aws_region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 2377
          to_port: 2377
          group_name: "{{ swarm_security_group_name }}"
        - proto: udp
          from_port: 8472
          to_port: 8472
          group_name: "{{ swarm_security_group_name }}"
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 3306
          to_port: 3306
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 7946
          to_port: 7946
          group_name: "{{ swarm_security_group_name }}"
        - proto: udp
          from_port: 7946
          to_port: 7946
          group_name: "{{ swarm_security_group_name }}"
        - proto: udp
          from_port: 4789
          to_port: 4789
          group_name: "{{ swarm_security_group_name }}"
        - proto: udp
          from_port: 2749
          to_port: 2749
          group_name: "{{ swarm_security_group_name }}"
      rules_egress:
        - proto: udp
          from_port: 8472
          to_port: 8472
          group_name: "{{ swarm_security_group_name }}"
        - proto: tcp
          from_port: 0
          to_port: 65535
          cidr_ip: 0.0.0.0/0
    register: sg
